### ISSUE TITLE
HemOnc acquisition failing - request times out

### ISSUE THREAD

**Issue by jsstevenson** [GenomicMedLab/wags-tails#46]
```
Traceback (most recent call last):
  File "/Users/jss009/code/therapy-normalization/src/therapy/cli.py", line 278, in <module>
    update_normalizer_db()
  File "/Users/jss009/code/therapy-normalization/.venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jss009/code/therapy-normalization/.venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/jss009/code/therapy-normalization/.venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jss009/code/therapy-normalization/.venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jss009/code/therapy-normalization/src/therapy/cli.py", line 274, in update_normalizer_db
    _update_normalizer(parsed_source_names, db, update_merged, use_existing)
  File "/Users/jss009/code/therapy-normalization/src/therapy/cli.py", line 184, in _update_normalizer
    _load_source(n, db, delete_time, processed_ids, use_existing)
  File "/Users/jss009/code/therapy-normalization/src/therapy/cli.py", line 108, in _load_source
    processed_ids += source.perform_etl(use_existing)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jss009/code/therapy-normalization/src/therapy/etl/base.py", line 108, in perform_etl
    self._extract_data(use_existing)
  File "/Users/jss009/code/therapy-normalization/src/therapy/etl/hemonc.py", line 29, in _extract_data
    data_files, self._version = self._data_source.get_latest(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jss009/code/therapy-normalization/.venv/lib/python3.12/site-packages/wags_tails/hemonc.py", line 152, in get_latest
    self._download_data(latest_version, file_paths)
  File "/Users/jss009/code/therapy-normalization/.venv/lib/python3.12/site-packages/wags_tails/hemonc.py", line 82, in _download_data
    download_http(
  File "/Users/jss009/code/therapy-normalization/.venv/lib/python3.12/site-packages/wags_tails/utils/downloads.py", line 123, in download_http
    with requests.get(
         ^^^^^^^^^^^^^
  File "/Users/jss009/code/therapy-normalization/.venv/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jss009/code/therapy-normalization/.venv/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jss009/code/therapy-normalization/.venv/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jss009/code/therapy-normalization/.venv/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jss009/code/therapy-normalization/.venv/lib/python3.12/site-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='dataverse.harvard.edu', port=443): Read timed out. (read timeout=30)
```

**Comment by mcannon068nw** [comment]
Whats the easiest way for me to replicate this timeout?

**Comment by jsstevenson** [comment]
Contacted Harvard Dataverse helpdesk, they indicated it was probably just a temporary outage. Seems to be working now.
